### PR TITLE
Development

### PR DESCRIPTION
**Pull request by auxibackup**
'Latest movie section' api working.

### CODE REVIEW

**Comment by auxibackup** [comment]
Do NOT merge, run it locally and let me know. This is a snippet of the 'Title section' under the search bar.

**Comment by auxibackup** [comment]
just need to input your API_KEY in the utils/config.js

**Comment by Javiercerna** [comment]
It looks really good!

image

**Review by Javiercerna — CHANGES_REQUESTED** [review]
Working fine :+1: But if you'd like to merge, please first pull the changes from the development upstream into your local branch

**Comment by auxibackup** [comment]
refactoring.

**Pull request closed without merging**
